apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        # Main application container
        - name: appointment-service
          image: bits2023mt03164/appointment_management:v1
          ports:
            - containerPort: 6000
        
        # MongoDB container
        - name: mongodb
          image: mongo:latest  # Official MongoDB image
          ports:
            - containerPort: 27017  # MongoDB default port
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db  # MongoDB data directory

      volumes:
        - name: mongo-data
          emptyDir: {}  # Use emptyDir volume for shared storage between containers

---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  type: NodePort
  selector:
    app: appointment-service
  ports:
    - port: 6000
      targetPort: 6000
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: NodePort
  selector:
    app: appointment-service
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30001  # You can change the port to whatever is available on your node