name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dkkh8788/appointment_management:$(date +%s)

    - name: Setup dockerbuildx
      uses: docker/setup-buildx-action@v1

    - name: Login Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push the image to DockerHub
      run: |
        docker build -t dkkh8788/appointment_management:latest .
        docker push dkkh8788/appointment_management:latest
